language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


before_install:
  # override default MAVEN_OPTS
  - echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

install: mvn clean install -B -DskipTests=true -s /home/travis/build/richfaces/richfaces/buildhive-settings.xml

script: mvn clean verify -Dintegration=wildfly90 -Dsmoke -s /home/travis/build/richfaces/richfaces/buildhive-settings.xml -Darquillian.maven.settings=/home/travis/build/richfaces/richfaces/buildhive-settings.xml

cache:
  directories:
  - '$HOME/.m2/repository'

sudo: false
