language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  firefox: latest-esr

before_install:
  # override default MAVEN_OPTS
  - echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

install: mvn clean install -B -DskipTests=true -s /home/travis/build/richfaces/richfaces/buildhive-settings.xml

# prepare environment for firefox
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # give xvfb some time to start
  - sleep 3
  # unpack and add firefox to path
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-latest-esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"

# use WildFly 9 so it can run with Java 7 (WildFly 10 requires Java 8)
script: mvn verify -Dintegration=wildfly90 -Dsmoke -s /home/travis/build/richfaces/richfaces/buildhive-settings.xml -Darquillian.maven.settings=/home/travis/build/richfaces/richfaces/buildhive-settings.xml -Dbrowser=firefox | awk '{ print strftime("%H:%M:%S"), $0; fflush(); }'

cache:
  directories:
  - '$HOME/.m2/repository'

sudo: false
